# Generated by Django 4.0.4 on 2022-11-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('useremail', models.EmailField(max_length=128, verbose_name='사용자이메일')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('bridge', models.CharField(max_length=128, verbose_name='교량 권한')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': 'breezy사용자',
                'verbose_name_plural': 'breezy사용자',
                'db_table': 'breezyuser',
            },
        ),
    ]
