# Generated by Django 4.0.4 on 2022-11-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='교량명')),
                ('length', models.CharField(default='', max_length=32, verbose_name='교량 길이')),
                ('section', models.CharField(default='', max_length=32, verbose_name='section')),
                ('writer', models.CharField(default='', max_length=32, verbose_name='등록자')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '교량',
                'verbose_name_plural': '교량',
                'db_table': 'bridges',
            },
        ),
    ]
